crud/urls.py
from django.conf.urls import url
from . import views

app_name = "crud"
urlpatterns = (
    url(r'^$', views.index, name='index'),
    url(r'^create_post/$', views.create_post, name='create_post'),
    url(r'^create/$', views.create, name = 'create'),
    url(r'^show/(?P<id>\d+)/$', views.show , name = 'show'),
    url(r'^edit/(?P<id>\d+)/$', views.edit , name = 'edit'),
    url(r'^update/(?P<id>\d+)/$', views.update , name = 'update'),
    url(r'^delete/(?P<id>\d+)/$', views.destroy, name= 'delete')
)

newapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^crud/', include('crud.urls')),
    url(r'^admin/', admin.site.urls),
]

crud/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Item(models.Model):
    title = models.CharField(max_length=100)
    post = models.TextField()

crud/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals

from django.shortcuts import render, redirect
from crud.models import Item

def index(request):
    item = Item.objects.all()
    context = {
        'item' : item
    }
    return render(request, 'crud/home.html', context)
def create_post(request):
    return render(request, 'crud/create.html')
def create(request):
    item = Item(
        title = request.POST['title'],
        post = request.POST['post']
    )
    item.save()
    return redirect('/crud')
def show(request, id):
    item = Item.objects.get(id = id)
    return render(request, 'crud/show.html', {
        'item' : item
    })
def edit(request, id):
    item = Item.objects.get(id = id)
    return render(request, 'crud/edit.html', {
        'item' : item
})
def update(request, id):
    item = Item.objects.get(id = id)
    item.title = request.POST['title']
    item.post = request.POST['post']
    item.save()
    return redirect('/crud')
def destroy(request, id):
    item = Item.objects.get(id = id)
    item.delete()
    return redirect('/crud')

crud/templates/crud/create.html
<!DOCTYPE html>
<html>
<head>
	<title>welcome my first django project</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'crud/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'crud/css/bootstrap.css' %}">
</head>
<body>
<div class="form-header">
	<div class="container">
		<div class="row">
			<h2>CRUD</h2>
			<nav class="navbar navbar-nav">
				<ul class="nav nav-pills">
					<li><a href="{% url 'crud:index' %}">Home</a></li>
				</ul>
			</nav>
			<div class="col-md-offset-3 col-md-6 text-center ">
				<form class="form-horizontal" action="{% url 'crud:create' %}" method="post">
					{% csrf_token %}
				  <fieldset>
				    <legend>Create post</legend>
				    <div class="form-group">
				      <label for="title" class="col-lg-2 control-label">Title</label>
				      <div class="col-lg-10">
				        <input type="text" class="form-control" id="title" name="title" placeholder="Title">
				      </div>
				    </div>
				    <div class="form-group">
				      <label for="textArea" class="col-lg-2 control-label">post body</label>
				      <div class="col-lg-10">
				        <textarea class="form-control" rows="3" name="post" id="textArea"></textarea>
				      </div>
				    </div>
				    <div class="form-group">
				    	<button type="submit" class="btn btn-success pull-right">Create</button>
				    </div>
				  </fieldset>
				</form>
			</div>
		</div>
	</div>
</div>

<script src="{% static 'crud/js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'crud/js/bootstrap.js' %}"></script>
</body>
</html>

crud/templates/crud/edit.html
<!DOCTYPE html>
<html>
<head>
	<title>welcome my first laravel project</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'crud/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'crud/css/bootstrap.css' %}">
</head>
<body>
<div class="form-header">
	<div class="container">
		<div class="row">
			<h2>CRUD</h2>
			<nav class="navbar navbar-nav">
				<ul class="nav nav-pills">
					<li><a href="{% url 'crud:index' %}">Home</a></li>
				</ul>
			</nav>
			<div class="col-md-offset-3 col-md-6 text-center ">
				<form class="form-horizontal" action="{% url 'crud:update' item.id %}" method="post">
					{% csrf_token %}
				  <fieldset>
				    <legend>Create post</legend>
				    <div class="form-group">
				      <label for="title" class="col-lg-2 control-label">Title</label>
				      <div class="col-lg-10">
				        <input type="text" class="form-control" name="title" value="{{item.title}}" id="title" placeholder="Title">
				      </div>
				    </div>
				    <div class="form-group">
				      <label for="textArea" class="col-lg-2 control-label">post body</label>
				      <div class="col-lg-10">
				        <textarea class="form-control" name="post" rows="3" id="textArea">{{item.post}}</textarea>
				      </div>
				    </div>
				    <div class="form-group">
				    	<button type="submit" class="btn btn-success pull-right">Update</button>
				    </div>
				  </fieldset>
				</form>
			</div>
		</div>
	</div>
</div>

<script src="{% static 'crud/js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'crud/js/bootstrap.js' %}"></script>
</body>
</html>

crud/templates/crud/home.html
<!DOCTYPE html>
<html>
<head>
	<title>welcome my first django project</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'crud/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'crud/css/bootstrap.css' %}">
</head>
<body>
<div class="form-header">
	<div class="container">
		<div class="row">
			<h2>CRUD</h2>
			<nav class="navbar navbar-nav">
				<ul class="nav nav-pills">
					<li><a href="{% url 'crud:create_post' %}">Create Post</a></li>
				</ul>
			</nav>
			<div class="col-md-offset-3 col-md-6 text-center ">
				<table class="table table-striped table-hover ">
				  <thead>
				    <tr class="tbl-header">
				      <th>Post Title</th>
				      <th>Action</th>
				      <th>Action</th>
				    </tr>
				  </thead>
				  <tbody>
				  {% for item in item %}
				    <tr>
						<td style="padding-top:10px"><a href="{% url 'crud:show' item.id %}"><strong>{{ item.title}}</strong></a></td>
						<td><a href="{% url 'crud:edit' item.id%}" class="btn btn-success">Update</a></td>
						<td><a href="{% url 'crud:delete' item.id %}" class="btn btn-danger">Delete</a></td>
				    </tr>
				  {% endfor %}
				  </tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script src="{% static 'crud/js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'crud/js/bootstrap.js' %}"></script>
</body>
</html>

crud/templates/crud/show.html
<!DOCTYPE html>
<html>
<head>
	<title>welcome my first django project</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'crud/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'crud/css/bootstrap.css' %}">
</head>
<body>
<div class="form-header">
	<div class="container">
		<div class="row">
			<h2>CRUD</h2>
			<nav class="navbar navbar-nav">
				<ul class="nav nav-pills">
					<li><a href="{% url 'crud:create_post' %}">Create Post</a></li>
				</ul>
				<ul class="nav nav-pills">
					<li><a href="{% url 'crud:index' %}">Home</a></li>
				</ul>
			</nav>
			<div class="col-md-offset-3 col-md-6 text-center ">
                <h2>{{ item.title }}</h2>
                <p>{{ item.post }}</p>
			</div>
		</div>
	</div>
</div>

<script src="{% static 'crud/js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'crud/js/bootstrap.js' %}"></script>
</body>
</html>